version: 2

models:
  - name: salaries
    columns:
      - name: country
        tests:
          - not_null
      - name: loaded_at
        tests:
          - not_null

  - name: agg
    columns:
      - name: country
        tests:
          - not_null
      - name: loaded_at
        tests: 
          - not_null
