version: 2

models:
  - name: agg
  columns:
    - country
      tests: not_null
    - loaded_at
      tests: not_null
  - name: salaries
  columns:
    - country
      tests: not_null
    - loaded_at
      tests: not_null
