salaries:
  target: local
  outputs:
    local:
      type: sqlite
      threads: 1
      database: 'salaries'
      schema: 'main'
      schemas_and_paths:
        main: 'file_path/database_name.db'
      schema_directory: ''